package tech.vvp.vvp.client.model;

import com.atsuishio.superbwarfare.client.model.entity.VehicleModel;
import com.atsuishio.superbwarfare.entity.vehicle.base.VehicleEntity;
import net.minecraft.util.Mth;
import tech.vvp.vvp.entity.vehicle.AjaxEntity;

public class AjaxModel extends VehicleModel<AjaxEntity> {

    // Generated by Track Builder - 56 tracks
// Pivot: [0, 18.50, 47.25]

    private static final int TRACK_COUNT = 56;
    private static final int MAX_IDX = 56;
    private static final float[][] KEYFRAMES = {
            {176.95f, 18.50f, 47.25f},
            {143.37f, 17.21f, 50.96f},
            {104.31f, 13.89f, 53.08f},
            {65.24f, 9.98f, 52.68f},
            {29.22f, 7.14f, 49.96f},
            {28.61f, 5.23f, 46.44f},
            {28.61f, 3.31f, 42.92f},
            {28.01f, 1.39f, 39.40f},
            {0.00f, 0.50f, 35.55f},
            {0.00f, 0.50f, 31.54f},
            {0.00f, 0.50f, 27.53f},
            {0.00f, 0.50f, 23.53f},
            {0.00f, 0.50f, 19.52f},
            {0.00f, 0.50f, 15.51f},
            {0.00f, 0.50f, 11.50f},
            {0.00f, 0.50f, 7.49f},
            {0.00f, 0.50f, 3.48f},
            {0.00f, 0.50f, -0.53f},
            {0.00f, 0.50f, -4.54f},
            {0.00f, 0.50f, -8.54f},
            {0.00f, 0.50f, -12.55f},
            {0.00f, 0.50f, -16.56f},
            {0.00f, 0.50f, -20.57f},
            {0.00f, 0.50f, -24.58f},
            {0.00f, 0.50f, -28.59f},
            {0.00f, 0.50f, -32.60f},
            {-7.35f, 0.57f, -36.60f},
            {-42.80f, 2.48f, -40.01f},
            {-42.80f, 5.21f, -42.95f},
            {-42.80f, 7.93f, -45.89f},
            {-41.56f, 10.56f, -48.90f},
            {-90.13f, 14.10f, -50.50f},
            {-143.57f, 17.56f, -48.75f},
            {-178.04f, 18.49f, -44.95f},
            {-179.93f, 18.50f, -40.94f},
            {-180.00f, 18.50f, -36.93f},
            {-180.00f, 18.50f, -32.93f},
            {-180.00f, 18.50f, -28.92f},
            {-180.00f, 18.50f, -24.91f},
            {-180.00f, 18.50f, -20.90f},
            {-180.00f, 18.50f, -16.89f},
            {-180.00f, 18.50f, -12.88f},
            {-180.00f, 18.50f, -8.87f},
            {-180.00f, 18.50f, -4.87f},
            {-180.00f, 18.50f, -0.86f},
            {-180.00f, 18.50f, 3.15f},
            {-180.00f, 18.50f, 7.16f},
            {-180.00f, 18.50f, 11.17f},
            {-180.00f, 18.50f, 15.18f},
            {-180.00f, 18.50f, 19.19f},
            {-180.00f, 18.50f, 23.19f},
            {-180.00f, 18.50f, 27.20f},
            {-180.00f, 18.50f, 31.21f},
            {-180.00f, 18.50f, 35.22f},
            {-179.99f, 18.50f, 39.23f},
            {-179.99f, 18.50f, 43.24f},
            {176.95f, 18.50f, 47.25f}
    };

    private static final float START_Y = 18.50f;
    private static final float START_Z = 47.25f;

    private float getKeyframeValue(float t, int component) {
        int wrapRange = TRACK_COUNT * 2;
        float normalized = (t / wrapRange) * MAX_IDX;
        int idx1 = Mth.clamp((int) normalized, 0, MAX_IDX);
        int idx2 = Mth.clamp(idx1 + 1, 0, MAX_IDX);
        float frac = normalized - (int) normalized;

        float p1 = KEYFRAMES[idx1][component];
        float p2 = KEYFRAMES[idx2][component];

        if (component == 0) {
            float diff = p2 - p1;
            if (diff > 180f) p2 -= 360f;
            else if (diff < -180f) p2 += 360f;
        }

        return Mth.lerp(frac, p1, p2);
    }

    @Override
    public float getBoneRotX(float t) {
        return getKeyframeValue(t, 0);
    }

    @Override
    public float getBoneMoveY(float t) {
        return getKeyframeValue(t, 1) - START_Y;
    }

    @Override
    public float getBoneMoveZ(float t) {
        return getKeyframeValue(t, 2) - START_Z;
    }

    @Override
    public int getDefaultWrapRange(VehicleEntity vehicle) {
        return TRACK_COUNT * 2;
    }
}
